# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(314, 124)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        self.lbl_title.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lbl_title.setFont(font)
        self.lbl_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_title.setText("")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_temp = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_temp.setFont(font)
        self.lbl_temp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_temp.setText("")
        self.lbl_temp.setObjectName("lbl_temp")
        self.horizontalLayout.addWidget(self.lbl_temp)
        self.lbl_picture = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_picture.sizePolicy().hasHeightForWidth())
        self.lbl_picture.setSizePolicy(sizePolicy)
        self.lbl_picture.setMinimumSize(QtCore.QSize(30, 30))
        self.lbl_picture.setMaximumSize(QtCore.QSize(30, 30))
        self.lbl_picture.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_picture.setText("")
        self.lbl_picture.setObjectName("lbl_picture")
        self.horizontalLayout.addWidget(self.lbl_picture)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_desc = QtWidgets.QLabel(Form)
        self.lbl_desc.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_desc.setFont(font)
        self.lbl_desc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_desc.setText("")
        self.lbl_desc.setObjectName("lbl_desc")
        self.verticalLayout.addWidget(self.lbl_desc)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
