# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\tab_on_5_days.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(True)
        self.lbl_current_date = QtWidgets.QLabel(Form)
        self.lbl_current_date.setGeometry(QtCore.QRect(10, 20, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_current_date.setFont(font)
        self.lbl_current_date.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_current_date.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_current_date.setObjectName("lbl_current_date")
        self.lw_days_weather_list = QtWidgets.QListWidget(Form)
        self.lw_days_weather_list.setGeometry(QtCore.QRect(10, 70, 591, 331))
        self.lw_days_weather_list.setAutoFillBackground(False)
        self.lw_days_weather_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lw_days_weather_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lw_days_weather_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lw_days_weather_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lw_days_weather_list.setObjectName("lw_days_weather_list")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_current_date.setText(_translate("Form", "Сегодня ДАТА"))
